/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.aControladorPrincipal;
import Controlador.bControladorClientes;
import Controlador.cControladorOperador;
import Modelo.aaCliente;
import Modelo.ddServicio;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author William
 */
public class ___FacturaPago extends javax.swing.JFrame {

    /**
     * Creates new form ___FacturaPago
     */
    public ___FacturaPago() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        lblCosto = new javax.swing.JLabel();
        lblCoche = new javax.swing.JLabel();
        btnCancelarFactura = new javax.swing.JButton();
        btnPagar = new javax.swing.JButton();
        btnConsultarFactura = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaServicios = new javax.swing.JTable();
        txtIdentificador = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/__Imagenes/LogoOscuro.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 150, 190));

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("NUESTRO REGISTRO.");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 830, 450, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("FACTURACIÓN TALLER UP-MOR");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 450, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("BOULEVARD CUAUHNAHUAC LOMAS DEL TEXCAL JIUTEPEC MOR.");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 450, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("DE DATOS, EN CASO CONTRARIO SE QUEDARA UN ADEUDO DE LOS SERVICIOS EN ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 810, 450, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("TOTAL A PAGAR:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 680, 150, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("INGRESE SU IDENTIFICADOR DE CLIENTE PARA CALCULAR EL MONTO A PAGAR:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 450, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("AL PAGAR EL CORRESPONDIENTE MONTO SE ELIMINARÁ SU DEUDA DE NUESTRA BASE");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 790, 450, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setText("$");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 660, 20, 40));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 700, 200, 20));

        lblCosto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCosto.setText("0");
        jPanel1.add(lblCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 660, 200, 50));

        lblCoche.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCoche.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblCoche, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 386, 310, 40));

        btnCancelarFactura.setBackground(new java.awt.Color(255, 204, 204));
        btnCancelarFactura.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        btnCancelarFactura.setText("CANCELER FACTURA");
        btnCancelarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarFacturaActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelarFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 720, 180, 50));

        btnPagar.setBackground(new java.awt.Color(255, 204, 204));
        btnPagar.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        btnPagar.setText("PAGAR");
        btnPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarActionPerformed(evt);
            }
        });
        jPanel1.add(btnPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 720, 180, 50));

        btnConsultarFactura.setBackground(new java.awt.Color(255, 204, 204));
        btnConsultarFactura.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        btnConsultarFactura.setText("CONSULTAR MI FACTURA");
        btnConsultarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarFacturaActionPerformed(evt);
            }
        });
        jPanel1.add(btnConsultarFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 220, -1));

        tablaServicios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MODELO", "SERVICIO", "COSTO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaServicios.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(tablaServicios);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 430, 260));

        txtIdentificador.setBackground(new java.awt.Color(204, 204, 255));
        txtIdentificador.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtIdentificador.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtIdentificador.setBorder(null);
        jPanel1.add(txtIdentificador, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 320, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarActionPerformed
        if("0".equals(lblCosto.getText())){
            JOptionPane.showMessageDialog(null, "El Identificador no se inserto, o usted aún no solicito algun servicio");
            txtIdentificador.setText("");
            lblCosto.setText("");
            btnConsultarFactura.setVisible(true);
            ControlPrincipal.mostrarVentanaSolicitarServicio();
        }else{
            ControlClientes.PagarDeuda(txtIdentificador.getText());
            DefaultTableModel modelo = (DefaultTableModel) tablaServicios.getModel();
            int a = tablaServicios.getRowCount()-1;
            for (int i = a; i >= 0; i--) {          
            modelo.removeRow(modelo.getRowCount()-1);
            }
            
            txtIdentificador.setText("");
            lblCosto.setText("");
            btnConsultarFactura.setVisible(true);
            ControlPrincipal.mostrarVentanaSolicitarServicio();
        }
        
        
    }//GEN-LAST:event_btnPagarActionPerformed

    private void btnConsultarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarFacturaActionPerformed
        aaCliente buscaCliente = ControlClientes.buscaCliente(txtIdentificador.getText());
        ArrayList<ddServicio> CargarMiFactura = ControlClientes.CargarMiFactura();
        DefaultTableModel modelo = (DefaultTableModel) tablaServicios.getModel();
        Object[] fila = new Object[modelo.getColumnCount()];
        
        if(buscaCliente == null){
            JOptionPane.showMessageDialog(null, "El ID de cliente no esta asociado a ninguno");
            txtIdentificador.setText("");
        }else{
            if(CargarMiFactura != null){
                int CostoTotal = 0;
                for (int i=0; i<CargarMiFactura.size(); i++){
                    if(CargarMiFactura.get(i).getIdentificadorCliente().equals(txtIdentificador.getText())){
                        fila[0] = CargarMiFactura.get(i).getCocheTrabajado();
                        fila[1] = CargarMiFactura.get(i).getTipoServicio();
                        fila[2] = CargarMiFactura.get(i).getCostoServicio();
                        CostoTotal += CargarMiFactura.get(i).getCostoServicio();
                        modelo.addRow(fila);
                    }  
                }
                lblCosto.setText(String.valueOf(CostoTotal));
                btnConsultarFactura.setVisible(false);
            }
        }
    }//GEN-LAST:event_btnConsultarFacturaActionPerformed

    private void btnCancelarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarFacturaActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) tablaServicios.getModel();
        int a = tablaServicios.getRowCount()-1;
        for (int i = a; i >= 0; i--) {          
        modelo.removeRow(modelo.getRowCount()-1);
        }
        
        txtIdentificador.setText("");
        lblCosto.setText("");
        btnConsultarFactura.setVisible(true);
        ControlPrincipal.mostrarVentanaSolicitarServicio();
    }//GEN-LAST:event_btnCancelarFacturaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(___FacturaPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(___FacturaPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(___FacturaPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(___FacturaPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ___FacturaPago().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarFactura;
    private javax.swing.JButton btnConsultarFactura;
    private javax.swing.JButton btnPagar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblCoche;
    private javax.swing.JLabel lblCosto;
    private javax.swing.JTable tablaServicios;
    private javax.swing.JTextField txtIdentificador;
    // End of variables declaration//GEN-END:variables
    private aControladorPrincipal ControlPrincipal;
    private bControladorClientes ControlClientes;
    private cControladorOperador ControlOperador;
      
    
    public void setObjetoControladorPrincipal(aControladorPrincipal ControlPrincipal) {
        this.ControlPrincipal = ControlPrincipal;
    }

    public void setObjetoControladorClientes(bControladorClientes ControlClientes) {
        this.ControlClientes = ControlClientes;
    }

    public void setObjetoControladorOperador(cControladorOperador ControlOperador) {
        this.ControlOperador = ControlOperador;
    }
}
