/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

import Controlador.aControladorPrincipal;
import Controlador.bControladorClientes;
import Controlador.cControladorOperador;
import Modelo.aaCliente;
import Modelo.bbEmpleado;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author William
 */
public class __ComprarAuto extends javax.swing.JFrame {

    /** Creates new form __ComprarAuto */
    public __ComprarAuto() {
        initComponents();
        //agregarVendedores();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblCoche2 = new javax.swing.JLabel();
        lblCoche1 = new javax.swing.JLabel();
        lblCochePrecio = new javax.swing.JLabel();
        comboCoches = new javax.swing.JComboBox<>();
        btnComprarCoche = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        lblCochePrecio1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtIdentificador = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/__Imagenes/ComprarCoche.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, -1, 298));

        jPanel3.setBackground(new java.awt.Color(91, 43, 130));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 80, 280));

        jPanel2.setBackground(new java.awt.Color(255, 164, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 0, 70, 280));

        jPanel4.setBackground(new java.awt.Color(247, 50, 63));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 70, 280));

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        jLabel4.setText("COSTO DEL VEHÍCULO");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 340, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("UP-MOR CARS VARIEDAD DE VEHÍCULOS:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, -1, 40));
        jPanel1.add(lblCoche2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, 310, 240));

        lblCoche1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lblCoche1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 310, 240));

        lblCochePrecio.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(lblCochePrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, 290, 50));

        comboVendedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboVendedoresActionPerformed(evt);
            }
        });
        jPanel1.add(comboVendedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 370, 220, 30));

        comboCoches.setBackground(new java.awt.Color(247, 50, 63));
        comboCoches.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        comboCoches.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Aqui", "Honda S2000 2004", "Nissan Skyline R34 1999", "Nissan 350z 2005", "BMW Serie 3 2003", "Mercedez Benz SL-500 2002", "Volkswagen Bettle 2004", "Ford Focus Wagon 2002", "Renault Clio 1.6 2004", "Ford F-150 Lightnight 2003" }));
        comboCoches.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        comboCoches.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCochesActionPerformed(evt);
            }
        });
        jPanel1.add(comboCoches, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, 340, 50));

        btnComprarCoche.setBackground(new java.awt.Color(247, 50, 63));
        btnComprarCoche.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnComprarCoche.setForeground(new java.awt.Color(255, 255, 255));
        btnComprarCoche.setText("LO QUIERO");
        btnComprarCoche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarCocheActionPerformed(evt);
            }
        });
        jPanel1.add(btnComprarCoche, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 460, 220, 40));

        btnRegresar.setBackground(new java.awt.Color(247, 50, 63));
        btnRegresar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.setText("CANCELAR");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 520, 220, 40));

        lblCochePrecio1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblCochePrecio1.setText("$");
        jPanel1.add(lblCochePrecio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, 50, 50));

        jLabel6.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        jLabel6.setText("VENDEDOR RESPONSABLE:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 350, 150, 20));

        txtIdentificador.setBackground(new java.awt.Color(204, 204, 255));
        txtIdentificador.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtIdentificador.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtIdentificador.setBorder(null);
        jPanel1.add(txtIdentificador, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 300, 220, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        jLabel7.setText("RECUERDE QUE PARA ADQUIRIR UN AUTO USTED NECESITA ESTAR REGISTRADO COMO CLIENTE");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 470, 20));

        jLabel8.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        jLabel8.setText("IDENTIFICADOR DE CLIENTE:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 280, 150, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboCochesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCochesActionPerformed
        if(comboCoches.getSelectedItem()=="Seleccione Aqui"){
            lblCoche1.setIcon(null);
            lblCoche2.setIcon(null);
            lblCochePrecio.setText(null);
        }else if (comboCoches.getSelectedItem()=="Honda S2000 2004"){
            ImageIcon img1 = new ImageIcon("src/__Imagenes/Coche-1.jpeg");
            ImageIcon img2 = new ImageIcon("src/__Imagenes/Coche-2.jpeg");
            lblCoche1.setIcon(img1);
            lblCoche2.setIcon(img2);
            lblCochePrecio.setText("165,000.00");
        }else if (comboCoches.getSelectedItem()=="Nissan Skyline R34 1999"){
            ImageIcon img1 = new ImageIcon("src/__Imagenes/Coche-3.jpg");
            ImageIcon img2 = new ImageIcon("src/__Imagenes/Coche-4.jpg");
            lblCoche1.setIcon(img1);
            lblCoche2.setIcon(img2);
            lblCochePrecio.setText("995,000.00");
        }else if (comboCoches.getSelectedItem()=="Nissan 350z 2005"){
            ImageIcon img1 = new ImageIcon("src/__Imagenes/Coche-5.jpg");
            ImageIcon img2 = new ImageIcon("src/__Imagenes/Coche-6.jpg");
            lblCoche1.setIcon(img1);
            lblCoche2.setIcon(img2);
            lblCochePrecio.setText("130,000.00");
        }else if (comboCoches.getSelectedItem()=="BMW Serie 3 2003"){
            ImageIcon img1 = new ImageIcon("src/__Imagenes/Coche-7.jpg");
            ImageIcon img2 = new ImageIcon("src/__Imagenes/Coche-8.jpg");
            lblCoche1.setIcon(img1);
            lblCoche2.setIcon(img2);
            lblCochePrecio.setText("150,000.00");
        }else if (comboCoches.getSelectedItem()=="Mercedez Benz SL-500 2002"){
            ImageIcon img1 = new ImageIcon("src/__Imagenes/Coche-9.jpg");
            ImageIcon img2 = new ImageIcon("src/__Imagenes/Coche-10.jpg");
            lblCoche1.setIcon(img1);
            lblCoche2.setIcon(img2);
            lblCochePrecio.setText("220,000.00");
        }else if (comboCoches.getSelectedItem()=="Volkswagen Bettle 2004"){
            ImageIcon img1 = new ImageIcon("src/__Imagenes/Coche-11.jpg");
            ImageIcon img2 = new ImageIcon("src/__Imagenes/Coche-12.jpg");
            lblCoche1.setIcon(img1);
            lblCoche2.setIcon(img2);
            lblCochePrecio.setText("98,000.00");
        }else if (comboCoches.getSelectedItem()=="Ford Focus Wagon 2002"){
            ImageIcon img1 = new ImageIcon("src/__Imagenes/Coche-13.jpg");
            ImageIcon img2 = new ImageIcon("src/__Imagenes/Coche-14.jpg");
            lblCoche1.setIcon(img1);
            lblCoche2.setIcon(img2);
            lblCochePrecio.setText("45,000.00");
        }else if (comboCoches.getSelectedItem()=="Renault Clio 1.6 2004"){
            ImageIcon img1 = new ImageIcon("src/__Imagenes/Coche-15.jpg");
            ImageIcon img2 = new ImageIcon("src/__Imagenes/Coche-16.jpg");
            lblCoche1.setIcon(img1);
            lblCoche2.setIcon(img2);
            lblCochePrecio.setText("55,000.00");
        }else if (comboCoches.getSelectedItem()=="Ford F-150 Lightnight 2003"){
            ImageIcon img1 = new ImageIcon("src/__Imagenes/Coche-17.jpg");
            ImageIcon img2 = new ImageIcon("src/__Imagenes/Coche-18.jpg");
            lblCoche1.setIcon(img1);
            lblCoche2.setIcon(img2);
            lblCochePrecio.setText("$90,000.00");
        }
    }//GEN-LAST:event_comboCochesActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        ControlPrincipal.mostrarVentanaClientes();
        comboVendedores.removeAllItems();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void comboVendedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboVendedoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboVendedoresActionPerformed

    private void btnComprarCocheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarCocheActionPerformed
        aaCliente buscaCliente = ControlClientes.buscaCliente(txtIdentificador.getText());
        
        if(comboCoches.getSelectedItem().toString() != "Seleccione Aqui"){
            
            if(comboVendedores.getSelectedItem().toString() != "Seleccione el vendedor"){
               
                if(buscaCliente == null){
                JOptionPane.showMessageDialog(null, "El identificador de cliente no esta asociado a ningún cliente");
            
                }else{
                    
                    ControlOperador.registraNuevaVenta(txtIdentificador.getText(), comboVendedores.getSelectedItem().toString(),comboCoches.getSelectedItem().toString());
                    JOptionPane.showMessageDialog(null, "Gracias por su compra");
                    comboVendedores.removeAllItems();
                    ControlPrincipal.mostrarVentanaClientes();
                } 
                
            }else{
                JOptionPane.showMessageDialog(null, "Seleccione quien le vendio el coche");
            }
            
        }else{
            JOptionPane.showMessageDialog(null, "Seleccione su coche a comprar");
        }
        
    }//GEN-LAST:event_btnComprarCocheActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(__ComprarAuto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(__ComprarAuto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(__ComprarAuto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(__ComprarAuto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new __ComprarAuto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComprarCoche;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> comboCoches;
    private final javax.swing.JComboBox<String> comboVendedores = new javax.swing.JComboBox<>();
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblCoche1;
    private javax.swing.JLabel lblCoche2;
    private javax.swing.JLabel lblCochePrecio;
    private javax.swing.JLabel lblCochePrecio1;
    private javax.swing.JTextField txtIdentificador;
    // End of variables declaration//GEN-END:variables
    private aControladorPrincipal ControlPrincipal;
    private bControladorClientes ControlClientes;
    private cControladorOperador ControlOperador;
      
    
    public void setObjetoControladorPrincipal(aControladorPrincipal ControlPrincipal) {
        this.ControlPrincipal = ControlPrincipal;
    }

    public void setObjetoControladorClientes(bControladorClientes ControlClientes) {
        this.ControlClientes = ControlClientes;
    }

    public void setObjetoControladorOperador(cControladorOperador ControlOperador) {
        this.ControlOperador = ControlOperador;
    }

    public void agregarVendedores() {
        try{
            comboVendedores.addItem("Seleccione el vendedor");
            ArrayList<bbEmpleado> valor = ControlOperador.cargarListaTecnicos();
 
            if(valor == null){
            JOptionPane.showMessageDialog(null, "Ningun vendedor disponible");
            
            }else{
                for (int i=0; i<valor.size(); i++){
                    if("Vendedor".equals(valor.get(i).getTipoEmpleado())){
                    comboVendedores.addItem(valor.get(i).getNombre().concat(" ").concat(valor.get(i).getApellido()));
                    }  
                }
            }   
            
        }catch(Exception ex){
            System.out.println(ex);
            ex.printStackTrace();
        }
        
         
        //ControlOperador.
        //comboVendedores.addItem("dickson");
    }

    
    
}
