/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.aControladorPrincipal;
import Controlador.bControladorClientes;
import Controlador.cControladorOperador;

/**
 *
 * @author William
 */
public class __SolicitarServicio extends javax.swing.JFrame {

    /**
     * Creates new form _SolicitarServicio
     */
    public __SolicitarServicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        btnImprimirFactura = new javax.swing.JButton();
        btnCarWash = new javax.swing.JButton();
        btnCambiarAceite = new javax.swing.JButton();
        btnRevisionMecanica = new javax.swing.JButton();
        btnCambiarNeumaticos = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/__Imagenes/MantenimientoAutomotriz.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 420, 402));

        jPanel2.setBackground(new java.awt.Color(91, 43, 130));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, -1));

        jPanel3.setBackground(new java.awt.Color(255, 164, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 450, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/__Imagenes/MechanicMaintain-removebg-preview.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 340, 30, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/__Imagenes/CarWash-removebg-preview.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, 30, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/__Imagenes/OilChange-removebg-preview.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 30, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/__Imagenes/ChangeTire-removebg-preview.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, 30, 40));

        btnRegresar.setBackground(new java.awt.Color(0, 0, 0));
        btnRegresar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.setText("ATRAS");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 550, 130, -1));

        btnImprimirFactura.setBackground(new java.awt.Color(0, 0, 0));
        btnImprimirFactura.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnImprimirFactura.setForeground(new java.awt.Color(255, 255, 255));
        btnImprimirFactura.setText("IMPRIMIR FACTURA DE PAGO");
        btnImprimirFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirFacturaActionPerformed(evt);
            }
        });
        jPanel1.add(btnImprimirFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 470, 430, 40));

        btnCarWash.setBackground(new java.awt.Color(247, 50, 63));
        btnCarWash.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCarWash.setForeground(new java.awt.Color(255, 255, 255));
        btnCarWash.setText("LAVADO DE AUTOS");
        btnCarWash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarWashActionPerformed(evt);
            }
        });
        jPanel1.add(btnCarWash, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, 380, 40));

        btnCambiarAceite.setBackground(new java.awt.Color(247, 50, 63));
        btnCambiarAceite.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCambiarAceite.setForeground(new java.awt.Color(255, 255, 255));
        btnCambiarAceite.setText("CAMBIO DE ACEITE");
        btnCambiarAceite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarAceiteActionPerformed(evt);
            }
        });
        jPanel1.add(btnCambiarAceite, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, 380, 40));

        btnRevisionMecanica.setBackground(new java.awt.Color(247, 50, 63));
        btnRevisionMecanica.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnRevisionMecanica.setForeground(new java.awt.Color(255, 255, 255));
        btnRevisionMecanica.setText("REVISIÓN MECÁNICA");
        btnRevisionMecanica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRevisionMecanicaActionPerformed(evt);
            }
        });
        jPanel1.add(btnRevisionMecanica, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 340, 380, 40));

        btnCambiarNeumaticos.setBackground(new java.awt.Color(247, 50, 63));
        btnCambiarNeumaticos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCambiarNeumaticos.setForeground(new java.awt.Color(255, 255, 255));
        btnCambiarNeumaticos.setText("CAMBIO DE NEUMATICOS");
        btnCambiarNeumaticos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarNeumaticosActionPerformed(evt);
            }
        });
        jPanel1.add(btnCambiarNeumaticos, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 270, 380, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/__Imagenes/LogoTaller.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 300, 50));

        jLabel7.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        jLabel7.setText("BIENVENIDO, SELECCIONE QUE SERVICIO DESEA REALIZAR A SU AUTO:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 380, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        ControlPrincipal.mostrarVentanaClientes();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnCarWashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarWashActionPerformed
        ControlPrincipal.mostrarVentanaCarWash();
    }//GEN-LAST:event_btnCarWashActionPerformed

    private void btnCambiarAceiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarAceiteActionPerformed
        ControlPrincipal.mostrarVentanaChangeOil();
    }//GEN-LAST:event_btnCambiarAceiteActionPerformed

    private void btnCambiarNeumaticosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarNeumaticosActionPerformed
        ControlPrincipal.mostrarVentanaCambiarNeumaticos();
    }//GEN-LAST:event_btnCambiarNeumaticosActionPerformed

    private void btnRevisionMecanicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRevisionMecanicaActionPerformed
        ControlPrincipal.mostrarVentanaRevisionMecanica();
    }//GEN-LAST:event_btnRevisionMecanicaActionPerformed

    private void btnImprimirFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirFacturaActionPerformed
        ControlPrincipal.mostrarVentanaImprimirFactura();
    }//GEN-LAST:event_btnImprimirFacturaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(__SolicitarServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(__SolicitarServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(__SolicitarServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(__SolicitarServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new __SolicitarServicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCambiarAceite;
    private javax.swing.JButton btnCambiarNeumaticos;
    private javax.swing.JButton btnCarWash;
    private javax.swing.JButton btnImprimirFactura;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnRevisionMecanica;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
    private aControladorPrincipal ControlPrincipal;
    private bControladorClientes ControlClientes;
    private cControladorOperador ControlOperador;
      
    
    public void setObjetoControladorPrincipal(aControladorPrincipal ControlPrincipal) {
        this.ControlPrincipal = ControlPrincipal;
    }

    public void setObjetoControladorClientes(bControladorClientes ControlClientes) {
        this.ControlClientes = ControlClientes;
    }

    public void setObjetoControladorOperador(cControladorOperador ControlOperador) {
        this.ControlOperador = ControlOperador;
    }
}
